// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwJc24_jqSQ_Q3H8y8ToOv7e4WcrGHvA',
    appId: '1:692713078513:web:fb2d423a5f57479d10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    authDomain: 'building-guard-app.firebaseapp.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
    measurementId: 'G-LYQE226Q4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7ZMbuPBNlAmRMhtJ4jZgCq5Qy2gr8ag',
    appId: '1:692713078513:android:977f247a01af8fab10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    storageBucket: 'building-guard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MIDrNPrlgmpOY2u8PNZ9JhfcrdgMgLM',
    appId: '1:692713078513:ios:9b9bdf150570c93a10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    storageBucket: 'building-guard-app.firebasestorage.app',
    iosBundleId: 'com.example.buildingGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0MIDrNPrlgmpOY2u8PNZ9JhfcrdgMgLM',
    appId: '1:692713078513:ios:9b9bdf150570c93a10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    storageBucket: 'building-guard-app.firebasestorage.app',
    iosBundleId: 'com.example.buildingGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwJc24_jqSQ_Q3H8y8ToOv7e4WcrGHvA',
    appId: '1:692713078513:web:a8a2693f16c1f37b10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    authDomain: 'building-guard-app.firebaseapp.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
    measurementId: 'G-GR0ZBFXKSC',
  );
}
